#!/usr/bin/ruby
# Copyright 2009 Max Howell <max@methylblue.com>
# Licensed as per the GPL version 3
require 'find'
require 'pathname'
$root = Pathname.new(__FILE__).realpath.dirname.parent.parent

def prune
  n=0
  dirs=Array.new
  $root.find do |path|
    if path.directory?
      name=path.relative_path_from($root).to_s
      if name == '.git' or name == 'Cellar' or name == 'Formula'
        Find.prune
      else
        dirs<<path
      end
    elsif path.symlink?
      resolved_path=path.dirname+path.readlink
      unless resolved_path.exist?
        path.unlink
        n+=1
      end
    end
  end
  # entries lists '.' and '..' so 2 is minimum basically
  dirs.sort.reverse_each { |d| d.rmdir if d.children.length == 0 }
  return n
end

case ARGV[0]
  when 'brew', 'install' then
    abort "You must specify a Formula" unless ARGV[1]
    ARGV.shift
    file="#{$root}/Formula/#{ARGV.shift}"
    file+='.rb' unless File.exist? file
    system "ruby #{file} #{ARGV.join ' '}"

  when 'rm' then
    path=$root+'Cellar'+ARGV[1]
    abort "#{ARGV[1]} is not installed" unless path.directory?
    path.rmtree
    prune
    puts "#{path} removed"

  when 'ln' then
    target=Pathname.new(ARGV[1])
    target=$root+'Cellar'+target unless target.exist?

    abort "#{target} is not a directory" unless target.directory?

    target=target.realpath

    if target.parent.parent == $root
      # we are one dir too high
      kids=target.children
      abort "#{target} is empty :(" if kids.length == 0
      abort "There are multiple versions of #{target.basename} installed please specify one" if kids.length > 1
      target=target.children.first
      abort "#{target} is not a directory!" unless target.directory?
    elsif target.parent.parent.parent != $root
      abort '#{target} is not a keg'
    end

    #TODO you should mkdirs as you find them and symlink files otherwise
    #TODO consider using hardlinks

    n=0
    target.find do |from|
      next if from == ARGV[1] #rubysucks

      to=$root+from.relative_path_from(target)

      if from.directory?
        to.mkpath unless to.exist?
      elsif from.file?
        tod=to.dirname
        Dir.chdir(tod) do
          `ln -sf "#{from.relative_path_from tod}"`
          n+=1
        end
      end
    end
    puts "Created #{n} links"

  when 'prune', 'pasteurize' then
    puts "Pruned #{prune} files"

  else
    puts "usage: #{$0} [prune] [ln path] [install pkg]"
end